<?php
/**
 * @file
 * Code for the OPL Storybook feature.
 */

include_once 'opl_storybook.features.inc';

/**
 * Implements hook_ctools_plugin_directory()
 */
function opl_storybook_ctools_plugin_directory($module, $plugin) {
  if ($module == "panels" && in_array($plugin, array('layouts', 'styles'))) {
    return "plugins/". $plugin;
  }

  if ($module == 'ctools' && !empty($plugin)) {
    return "plugins/". $plugin;
  }
}
